// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: streamconnection.proto

#include "streamconnection.pb.h"
#include "streamconnection.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace streamconnection {

static const char* streamconnection_method_names[] = {
  "/streamconnection.streamconnection/GetValues",
};

std::unique_ptr< streamconnection::Stub> streamconnection::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< streamconnection::Stub> stub(new streamconnection::Stub(channel, options));
  return stub;
}

streamconnection::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetValues_(streamconnection_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::streamconnection::Request, ::streamconnection::Response>* streamconnection::Stub::GetValuesRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::streamconnection::Request, ::streamconnection::Response>::Create(channel_.get(), rpcmethod_GetValues_, context);
}

void streamconnection::Stub::async::GetValues(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::streamconnection::Request,::streamconnection::Response>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::streamconnection::Request,::streamconnection::Response>::Create(stub_->channel_.get(), stub_->rpcmethod_GetValues_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::streamconnection::Request, ::streamconnection::Response>* streamconnection::Stub::AsyncGetValuesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::streamconnection::Request, ::streamconnection::Response>::Create(channel_.get(), cq, rpcmethod_GetValues_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::streamconnection::Request, ::streamconnection::Response>* streamconnection::Stub::PrepareAsyncGetValuesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::streamconnection::Request, ::streamconnection::Response>::Create(channel_.get(), cq, rpcmethod_GetValues_, context, false, nullptr);
}

streamconnection::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      streamconnection_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< streamconnection::Service, ::streamconnection::Request, ::streamconnection::Response>(
          [](streamconnection::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::streamconnection::Response,
             ::streamconnection::Request>* stream) {
               return service->GetValues(ctx, stream);
             }, this)));
}

streamconnection::Service::~Service() {
}

::grpc::Status streamconnection::Service::GetValues(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::streamconnection::Response, ::streamconnection::Request>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace streamconnection

